export const cardsInitialState = [
  {
    id: "KJADCD123",
    tableId: "T3",
    header: "Page d'acceuil",
    body: "Mise en place de la page d'acceuil en se basant sur la maquette",
    footer: "Le 11/02/22 de Alexandre Durand",
  },
  {
    id: "KJADCD124",
    tableId: "T2",
    header: "Page de connexion",
    body: "Mise en place de la page de connexion en se basant sur la maquette",
    footer: "Le 11/02/22 de Alexandre Durand",
  },

  {
    id: "KJADCD109",
    tableId: "T1",
    header: "Page  d'achat",
    body: "Mise en place de la page d'achat en se basant sur la maquette",
    footer: "Le 11/02/22 de Alexandre Durand",
  },

  {
    id: "KJADCD108",
    tableId: "T1",
    header: "Page du panier",
    body: "Mise en place de la page du panier en se basant sur la maquette",
    footer: "Le 11/02/22 de Alexandre Durand",
  },

  {
    id: "KJADCD089",
    tableId: "T3",
    header: "Page de profil",
    body: "Mise en place de la page de profil en se basant sur la maquette",
    footer: "Le 11/02/22 de Alexandre Durand",
  },
  {
    id: "KJADCD678",
    tableId: "T1",
    header: "Page dashboard",
    body: "Mise en place de la page dashboard en se basant sur la maquette",
    footer: "Le 11/02/22 de Alexandre Durand",
  },
  {
    id: "KJADCD127",
    tableId: "T1",
    header: "Page d'administration",
    body: "Mise en place de la page d'administration en se basant sur la maquette",
    footer: "Le 11/02/22 de Alexandre Durand",
  },
  {
    id: "KJADCD128",
    tableId: "T1",
    header: "Page de configuration",
    body: "Mise en place de la page de configuration en se basant sur la maquette",
    footer: "Le 11/02/22 de Alexandre Durand",
  },
  {
    id: "KJADCD129",
    tableId: "T0",
    header: "Page 404",
    body: "Mise en place de la page 404 en se basant sur la maquette",
    footer: "Le 11/02/22 de Alexandre Durand",
  },
  {
    id: "KJADCD110",
    tableId: "T0",
    header: "Page d'erreur",
    body: "Mise en place de la page d'erreur en se basant sur la maquette",
    footer: "Le 11/02/22 de Alexandre Durand",
  },
  {
    id: "KJADCD111",
    tableId: "T1",
    header: "Page de contact",
    body: "Mise en place de la page de contact en se basant sur la maquette",
    footer: "Le 11/02/22 de Alexandre Durand",
  },
  {
    id: "KJADCD131",
    tableId: "T4",
    header: "Page de produit",
    body: "Mise en place de la page de produit en se basant sur la maquette",
    footer: "Le 11/02/22 de Alexandre Durand",
  },
  {
    id: "KJADCD123",
    tableId: "T5",
    header: "Choix des technologies",
    body: "Définir les différentes technologies qui seront utilisé sur le projet. Framework frontend, pré processeur CSS, Framework Backend et OS du serveur de production",
    footer: "Le 11/02/22 de Alexandre Durand",
  },
  {
    id: "KJADCD193",
    tableId: "T5",
    header: "Architecture du projet",
    body: "Conception et diagrammes permettant de définir la structure du projet",
    footer: "Le 11/02/22 de Alexandre Durand",
  },
  {
    id: "KJADCD923",
    tableId: "T5",
    header: "Mise en place de l'environnement",
    body: "Création du templates de base et des sous dossiers nécessaires",
    footer: "Le 11/02/22 de Alexandre Durand",
  },
  {
    id: "KJADCD628",
    tableId: "T1",
    header: "Page de details produit",
    body: "Mise en place de la page de details en se basant sur la maquette",
    footer: "Le 11/02/22 de Alexandre Durand",
  },

  {
    id: "KJADCD998",
    tableId: "T1",
    header: "Page de vente",
    body: "Mise en place de la page de  vente en se basant sur la maquette",
    footer: "Le 11/02/22 de Alexandre Durand",
  },
];
